### ISSUE TITLE
Loss of external internet connection causes runaway Pybrake process

### ISSUE THREAD

**Issue by abigail-rolling** [airbrake/pybrake#112]
We use pybrake in a Flask app running in a docker container that is intended to be deployed on local networks with external internet access, not in the cloud. We have chosen to configure it using the logging integration instead of the Flask integration. Recently, one of our team members discovered that if pybrake is unable to successfully send a notice to the airbrake.io server, it enters a loop that eventually uses up all local memory then crashes. It appears that failing to connect to its home server throws an exception, which is logged to Airbrake as an error, which fails to connect and throw an exception, ad infinitum. Is this a known bug or configuration option? 

Version: up to and including 0.4.2

Very partial stdout log output:
```
2019-09-26 18:47:38,766 notifier.py:152 pybrake ERROR - <urlopen error [Errno -2] Name or service not known>
[2019-09-26 18:47:38,766] {notifier:152} ERROR - <urlopen error [Errno -2] Name or service not known>
2019-09-26 18:47:38,779 notifier.py:152 pybrake ERROR - <urlopen error [Errno -2] Name or service not known>
[2019-09-26 18:47:38,779] {notifier:152} ERROR - <urlopen error [Errno -2] Name or service not known>
```

**Comment by vmihailenco** [comment]
@anmic pybrake should check if the error originates from pybrake source code and ignore such errors. You can try to check backtrace filename.

**Comment by vmihailenco** [comment]
Something like in https://github.com/airbrake/pybrake/pull/113 but for real exceptions

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/airbrake/pybrake/commit/7841eee7f259f8b9bbe8b0b0642b3cb3556fc3f7
