### ISSUE TITLE
Broken Flask sqlalchemy integration

### ISSUE THREAD

**Issue by jordanhamill** [airbrake/pybrake#117]
pybrake version: 0.4.3

### Issue 1
If flask-sqlalchemy is importable but not yet configured, `flask.init_app` will throw. We share a virtual env between multiple services and at least 1 of these doesn't setup flask-sqlalchemy and crashes.

There should be some docs around the flask-sqlalchemy integration and it shouldn't crash if flask-sqlalchemy is not set up. 

### Issue 2
`SQLAlchemy(...).init_app` breaks pybrake integration because flask-sqlalchemy can't get the app outside of `app_context`

```py
def test_pybrakes_sqlalchemy_integration():
    from flask_sqlalchemy import SQLAlchemy

    app = Flask("test")
    app.config["PYBRAKE"] = ...
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///:memory"
    db = SQLAlchemy(app)
    app = pybrake.flask.init_app(app) # ok

def test_pybrakes_sqlalchemy_integration_init_app():
    from flask_sqlalchemy import SQLAlchemy

    app = Flask("test")
    app.config["PYBRAKE"] = ...
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///:memory"
    SQLAlchemy(...).init_app(app)
    app = pybrake.flask.init_app(app) # breaks because `flask-sqlalchemy` has no reference to `app` and not inside app_context
```

  File \"app/error_reporting/flask.py\", line 53, in initialize_airbrake
    app = pybrake.flask.init_app(app)

  File \".cache/pypoetry/virtualenvs/app/lib/python3.6/site-packages/pybrake/flask.py\", line 91, in init_app
    _sqla_instrument(app)
  File \".cache/pypoetry/virtualenvs/app/lib/python3.6/site-packages/pybrake/flask.py\", line 143, in _sqla_instrument
    engine = sqla.db.get_engine()
  File \".cache/pypoetry/virtualenvs/app/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py\", line 946, in get_engine
    app = self.get_app(app)
  File \".cache/pypoetry/virtualenvs/app/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py\", line 982, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/."
```

**Comment by vmihailenco** [comment]
Thanks for the report - please try v0.4.4
