### ISSUE TITLE
Sending notifications on exceptions at Celery tasks stopped after 0.4.5 upgrade

### ISSUE THREAD

**Issue by dios231** [airbrake/pybrake#122]
We use celery for monitoring celery tasks. Before the 0.4.5 upgrade, Airbrake was getting notified on Celery task exceptions. After the 0.4.5 this stopped and we can only manually notify Airbrake through `notifier.notify(err)`

the setup is the following
```
    notifier = pybrake.Notifier(project_id=settings.AIRBRAKE['project_id'],
                                project_key=settings.AIRBRAKE['project_key'],
                                environment="enviropment")
    patch_celery(notifier)

def add(x, y):
     raise ValueError("bad luck")
```

**Comment by phumpal** [comment]
@dios231 what was the previous version of pybrake?

**Comment by dios231** [comment]
0.4.2

**Comment by phumpal** [comment]
Hmm, git tags are missing for 0.4.1 - 0.4.3. 

> 0.4.2

Thanks for letting us know I'll take a look.

**Comment by phumpal** [comment]
@dios231 I can't seem to reproduce the desired behavior using v0.4.2.

Can you provide a gist w/working example?

**Comment by scottsbaldwin** [comment]
Closing since there was no response. Please reopen if necessary.
