### ISSUE TITLE
Add SQLalchemy integration

### ISSUE THREAD

**Issue by toloco** [airbrake/pybrake#123]
As a user of Airbrake, I'd like to have an SQLAlchemy integration

**Comment by toloco** [comment]
It should be easier as Airbrake already has SQL for Django integration

**Comment by scottsbaldwin** [comment]
Thanks for the suggestion @toloco. We are currently working on some improvements and new integrations for Pybrake. I'll consult with our team and see if this is something we can prioritize.

**Comment by scottsbaldwin** [comment]
Are there any specific things you're looking for in an integration with SQLAlchemy?
