### ISSUE TITLE
Notifier incorrectly returning errors

### ISSUE THREAD

**Issue by sutera** [airbrake/pybrake#130]
notifier running in k8s in gcp returns `notifier.py:179 pybrake ERROR - airbrake: unexpected response status_code=500` sporadically. Even though the message arrives in Airbrake correctly.

Other erroneous messages from pybrake I see are

`routes.py:133 pybrake ERROR - airbrake: unexpected response status_code=500`
and
`routes.py:119 pybrake ERROR - The read operation timed out`

even on successful responses, when no notification is expected.

**Comment by phumpal** [comment]
@sutera there was an outage last week which caused sporadic availability of the API. 

https://status.airbrake.io/incidents/qvplsnzb6kfz

I suspect the timestamp for those log messages should match up.

**Comment by phumpal** [comment]
@sutera I'm going to close this out as stale.

Happy to discuss [improving this](https://github.com/airbrake/pybrake/blob/master/pybrake/notifier.py#L174-L183) should the behavior not be ideal.
