### ISSUE TITLE
Flask integration order of filters does not apply blocklist to request object

### ISSUE THREAD

**Issue by danman01** [airbrake/pybrake#132]
Hello, I'm noticing that with the flask integration, there is a filter added that adds the request object to the params section of the notice. That is great and contains useful info, like the JSON payload. However, that filter occurs _after_ the make_blacklist_filter is applied, so the blocklist doesn't operate on the request object. And it turns out that request -> json contains much of the info we want to block. 

So I am getting around that order of filters by redoing the blocklist filtering after calling init_app:

```
        app = pybrake.flask.init_app(app)
        notifier = app.extensions['pybrake']
        # calling the make_blacklist_filter again, even though it occurs during init_app,
        # so that the request info also gets filtered
        notifier.add_filter(pybrake.notifier.make_blacklist_filter(my_blocklist))
```

I don't have a fix in mind, but thought it should be mentioned.

Using pybrake version 0.4.6

**Comment by danman01** [comment]
I would suggest removing this bit from `notifier.py#__init__`:
```
# maybe with a flag, like add_blocklist_filter = False ?

keys_blacklist = kwargs.get(
            "keys_blacklist", [re.compile("password"), re.compile("secret")]
        )
        self.add_filter(make_blacklist_filter(keys_blacklist))
```

and adding this in `flask.py#init_app`:
```
notifier.add_filter(request_filter)
# previous code...
#
keys_blacklist = app.config["PYBRAKE"].get(
            "keys_blacklist", [re.compile("password"), re.compile("secret")]
        )
self.add_filter(make_blacklist_filter(keys_blacklist))
#
# rest of code...
```

**Comment by scottsbaldwin** [comment]
@salonijain0918 is looking into this now...

**Comment by smurf-U** [comment]
@scottsbaldwin It's now resolved and available.

**Comment by kyrylo** [comment]
@smurf-U you can close issues once a corresponding PR is merged.
