### ISSUE TITLE
blocklist_filter attempts to change Immutable

### ISSUE THREAD

**Issue by danman01** [airbrake/pybrake#133]
Seeing this error with following stack trace -- it looks like if an object with multiple levels of nested objects make its way to the pybrake blocklist_filter, the filter attempts to set the value of one of the nested keys to "filtered". However, if this value is of type `ImmutableMultiDict`, an exception is raised. 
```
<FrameSummary ..python_path../site-packages/pybrake/blacklist_filter.py, line 23 in _filter_dict>, <FrameSummary ..python_path../site-packages/werkzeug/datastructures.py, line 200 in __setitem__>, <FrameSummary..python_path../site-packages/werkzeug/datastructures.py, line 36 in is_immutable>]' e="'ImmutableMultiDict' objects are immutable"
```

blocklist_filter code:
```
def make_blacklist_filter(keys_blacklist):
    def blacklist_filter(notice):
        for key in _NOTICE_KEYS:
            if key in notice:
                _filter_dict(notice[key], keys_blacklist)
        return notice

    return blacklist_filter


def _filter_dict(d, keys_blacklist):
    for key, value in d.items():
        if _is_blacklisted(key, keys_blacklist):
            d[key] = _FILTERED
            continue
        if isinstance(value, collections.abc.Mapping):
            _filter_dict(value, keys_blacklist)
```

In `_filter_dict`, is there a way to check that the value is mutable before changing it? Or could the `d[key] = _FILTERED` operation be wrapped in a try / except `TypeError` block?

**Comment by scottsbaldwin** [comment]
Thanks @danman01 for reporting this. Sorry we haven't responded until now. We will take a look.

**Comment by smurf-U** [comment]
@scottsbaldwin It's now resolved and available.

**Comment by kyrylo** [comment]
@smurf-U you can close issues once a corresponding PR is merged.
