### ISSUE TITLE
pybrake possible broken for non-Cython applications.

### ISSUE THREAD

**Issue by badcure** [airbrake/pybrake#155]
Possibly a regression from: https://github.com/airbrake/pybrake/issues/86

I have not tested all the version, but when running with `pybrake==0.4.6`, the application starts up without an issue on AWS Lambdas. 

When simply changing to `pybrake==1.0.3`, the following error occurs while attempting to import: 
```
Traceback (most recent call last):
  File "/var/task/es_thin_lambdas/base.py", line 8, in <module>
    import pybrake
  File "/var/task/pybrake/__init__.py", line 1, in <module>
    from .notifier import Notifier
  File "/var/task/pybrake/notifier.py", line 15, in <module>
    from .routes import _Routes
  File "/var/task/pybrake/routes.py", line 8, in <module>
    from .tdigest import as_bytes, TDigestStat
  File "/var/task/pybrake/tdigest.py", line 3, in <module>
    import tdigest
  File "/var/task/tdigest/__init__.py", line 1, in <module>
    from .tdigest import TDigest
  File "/var/task/tdigest/tdigest.py", line 5, in <module>
    from accumulation_tree import AccumulationTree
  File "/var/task/accumulation_tree/__init__.py", line 2, in <module>
    from .accumulation_tree import AccumulationTree
ModuleNotFoundError: No module named 'accumulation_tree.accumulation_tree'
```

**Comment by scottsbaldwin** [comment]
Thanks @badcure, we will take a look. Sorry for the long delay in responsiveness.

**Comment by scottsbaldwin** [comment]
@salonijain0918 it looks like https://github.com/wavefrontHQ/wavefront-pyformance/issues/22#issuecomment-483438333 may have some clues for us with this issue.

**Comment by otakusid** [comment]
any workaround for this issue?

**Comment by scottsbaldwin** [comment]
> any workaround for this issue?

Not yet. We have had some things come up and we haven't been able to investigate this like we had hoped.

**Comment by smurf-U** [comment]
@otakusid 'Container image' can be used to build lambda functions for you.

**Comment by smurf-U** [comment]
@otakusid I'm closing this issue for now. As mentioned, give it a shot. It'll work. Thanks.
