### ISSUE TITLE
[PROPOSAL] Disable stats calls by default

### ISSUE THREAD

**Issue by 00dav00** [airbrake/pybrake#161]
Hi, I would like to propose disable calling stats endpoints by default.

I was working in a project were pyVCR was used to record interactions with external systems. Calls to the query and performance stats endpoints were showing up here and there, making the builds in CI fail because pyVCR didn't find the stat calls in the cassettes.

![Screenshot from 2021-07-17 10-33-38](https://user-images.githubusercontent.com/9206778/126042219-3192ae8b-6457-4ef4-8c91-ca21356268a7.png)

I think this feature should be disabled by default or the config param should be mandatory so that enabling/disabling these calls is explicit.

Please let me know WDYT. Thank you!

**Comment by scottsbaldwin** [comment]
@00dav00 thanks for your proposal. Have you tried initializing your pybrake Notifier during CI with the option disabled for performance stats?

```
notifier = pybrake.Notifier(project_id=123,
                            project_key='FIXME',
                            environment='production',
                            performance_stats=False,
                            query_stats=False,
                            queue_stats=False
)
```

**Comment by 00dav00** [comment]
Hi @scottsbaldwin , yes, what I propose is that 1 of these 2 changes is applied:
- Make `query_stats`, `queue_stats` and  `performance_stats` false by default
- Change `query_stats`, `queue_stats` and  `performance_stats` params to be explicitly set instead of having defaults.

WDYT?

**Comment by scottsbaldwin** [comment]
Providing performance monitoring related to queries, job queues, and routes is something we want to promote. There are use cases, as you pointed out, in which disabling those features is desired. We would not want it disabled by default.

I will point out that our documentation could be improved. In order to find those configuration options, I had to read the pybrake code directly. This is probably a better place to make a change than by adjusting the default value of the configuration option.

**Comment by 00dav00** [comment]
I guess that can help too, I honestly think it should be the other way around but you probably now the use cases best. Thanks @scottsbaldwin

**Comment by goetzc** [comment]
Hi. This affected my project too and had the same issue. It's a very odd default value, IMO.

On other big players, such as Sentry, this is disabled by default, as the main purpose of the tool is to send "brakes", not performance statics, and having this option on by default has small but still present performance impact.
