### ISSUE TITLE
Turn Notifier class into a singleton?

### ISSUE THREAD

**Issue by giampaolo** [airbrake/pybrake#168]
Hello. I'm in a situation where I have to configure pybrake twice, once globally and once for a flask app (via `pybrake.flask.init_app`).
Because of this, 2 `Notifier` instances get created, which is bad because each one spawns a thread pool. In order to avoid that, I could e.g. pass a `Notifier` instance to `pybrake.flask.init_app`, but the function signature doesn't allow that. I noticed that internally pybrake uses a `get_global_notifier()` function, which would serve the purpose pretty well. However, I see that it is only being used by `pybrake/django.py` and `pybrake/logging.py` modules. I think pybrake should either:

1) never instantiate `Notifier()` class directly and instead always rely on `get_global_notifier()`
2) turn `Notifier` class into a singleton, as in:

```python
class _Singleton(type):
    _instances = {}
    def __call__(cls, *args, **kw):
        if cls not in cls._instances:
            cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kw)
        return cls._instances[cls]

class Notifier(metaclass=_Singleton):
    ...
```

Thoughts?

**Comment by scottsbaldwin** [comment]
Thanks @giampaolo for the suggestion. @salonijain0918 will look into this.
