### ISSUE TITLE
Pypi Source not working

### ISSUE THREAD

**Issue by vigneshhari** [airbrake/pybrake#182]
The latest Build in PyPi seems to be missing the source code. Ref : https://pypi.org/project/pybrake/1.0.5/#files
Attaching a screenshot as well.
![image](https://user-images.githubusercontent.com/14056798/162947230-3caa1e71-4e90-4fd0-b159-eb27dba1e427.png)

**Comment by smurf-U** [comment]
@vigneshhari Thank you for informing us. Please download the latest version. You will be given access to all of the files.
