### ISSUE TITLE
Errors filtered out when middleware involve in backtrace

### ISSUE THREAD

**Issue by camuthig** [airbrake/pybrake#191]
When performance stats are enabled using the Django integration, SQL errors are not delivered to Airbrake.

I am able to reproduce this, but I am not sure the best way to introduce a fix to the project. What I found is that when performance stats are enabled, all of the SQL queries are wrapped in the `CursorWrapper` class from the `pybrake` module. This results in the the `CursorWrapper._record` and `CursorWrapper.execute` functions being in the traceback of the exception. When this is combined with the `pybrake_error_filter`, it means that these errors will always be filtered.

I created a simple Django project that recreates the issue in its tests: https://github.com/camuthig/pybrake-django-bug

**Comment by smurf-U** [comment]
Thanks @camuthig for reporting this. We'll get it taken care of as quickly as possible.

**Comment by smurf-U** [comment]
Thanks @camuthig for reporting this. We'll get it taken care of as quickly as possible.
