### ISSUE TITLE
UnboundLocalError: local variable 'source' referenced before assignment

### ISSUE THREAD

**Issue by cj-murphy** [airbrake/pybrake#21]
When using global `excepthook` exception catching and throwing an uncaught exception pybrake fails to send the error through to airbrake. The error occurs in code_hunks.py line 28 where `source` is undefined.

Python version: 3.6.4
Pybrake version: 0.3.2

```
import pybrake
import logging
import sys


def main():
    notifier = pybrake.Notifier(project_id=ID,
                                project_key='KEY',
                                environment='production')

    logger = logging.getLogger('test')
    logger.addHandler(
        pybrake.LoggingHandler(notifier=notifier, level=logging.ERROR)
    )

    def handle_exception(exc_type, exc_value, exc_traceback):
        logger.error("Uncaught exception", exc_info=(exc_type, exc_value, exc_traceback))

    sys.excepthook = handle_exception

    raise Exception('show-me-in-airbrake')


if __name__ == "__main__":
    main()
```

I can temporarily fix this by moving line 28/29 inside the try/except above.

Trace:

> --- Logging error ---
> Traceback (most recent call last):
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/logging.py", line 38, in emit
>     notice = self.build_notice(record)
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/logging.py", line 45, in build_notice
>     notice['errors'].append(self._build_error(record))
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/logging.py", line 52, in _build_error
>     return self._build_error_from_exc_info(record.exc_info)
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/logging.py", line 63, in _build_error_from_exc_info
>     backtrace = self._notifier._build_backtrace_tb(tb)
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/notifier.py", line 237, in _build_backtrace_tb
>     f = self._build_frame(frame, lineno)
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/notifier.py", line 274, in _build_frame
>     module_name=module_name)
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/notifier.py", line 284, in _frame_with_code
>     lines = get_code_hunk(filename, line, loader=loader, module_name=module_name)
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/code_hunks.py", line 6, in get_code_hunk
>     lines = _get_lines_from_file(filename, loader=loader, module_name=module_name)
>   File "/Users/cj/.local/share/virtualenvs/tmp/lib/python3.6/site-packages/pybrake/code_hunks.py", line 28, in _get_lines_from_file
>     if source is not None:
> UnboundLocalError: local variable 'source' referenced before assignment

**Comment by vmihailenco** [comment]
Thanks for the report - this should be fixed in v0.3.3
