### ISSUE TITLE
Can't send an Airbrake notification from within a Django test?

### ISSUE THREAD

**Issue by khpeek** [airbrake/pybrake#24]
As described in [this StackOverflow question](https://stackoverflow.com/questions/50635038/airbrake-notifications-disabled-in-django-tests), I'm unable to send Airbrake notifications from a Django test, although I was able to send one from the Django shell. 

In the end, I worked around the problem by turning `logger.error` into a `Mock` object. I wonder, however, why the `send_notice` method is not being called in the test case? Also, it might be useful for Airbrake to include some best practices for unit testing manually logged errors in its documentation.

**Comment by vmihailenco** [comment]
Can you try `notify_sync` or `send_notice_sync`? By default pybrake sends errors asynchronously.

**Comment by khpeek** [comment]
I don't have the example at my fingertips, but as far as I can tell from [the `Notifier` source code](https://github.com/airbrake/pybrake/blob/24facc22237f2c74f3e778a2d0578a50568deefe/pybrake/notifier.py), `send_notice` itself calls `send_notice_sync` - specifically, it submits it to a [`ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor). So if `send_notice` is not getting called, I don't see how `send_notice_sync` would?

**Comment by vmihailenco** [comment]
send_notice is async version of sent_notice_sync. And notify is async version of notify_sync. Did you try notify_sync?
