### ISSUE TITLE
Django project not alerting airbrake on logger.error

### ISSUE THREAD

**Issue by sandeepbalagopal09** [airbrake/pybrake#246]
I have a Django project set up and followed the doc https://docs.airbrake.io/docs/platforms/framework/python/django/ to integrate airbrake. I am getting airbrake alert on exceptions when we have yellow page. But the manual logger.error are not alerting aibrake.
This is my code.
```
import logging
from django.shortcuts import HttpResponse


logger = logging.getLogger()

def test(request):
    logger.error("Test airbrake")
    return HttpResponse("test")
```

If I follow this https://github.com/airbrake/pybrake#logging-integration and add handler then I would get the alert. But that is not the right way to approach it. If I want to switch from airbrake to another library in future then I have to remove the airbrake handler from all the files where I have log. Is this the expected behavior ? Shouldn't creating a logger without the airbrake handler send alert based on the logging type ?

**Comment by smurf-U** [comment]
Thanks @sandeepbalagopal09  for reporting this. 

Can you confirm which version of pybrake and Django you are using?

**Comment by sandeepbalagopal09** [comment]
@smurf-U 
Django==4.0.4
pybrake==1.10.0

**Comment by smurf-U** [comment]
@sandeepbalagopal09 

To do this, you must specify the handler name of your configuration logger when creating a new logger instance. For instance, assuming your setup is as follows

```py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'airbrake': {
            'level': 'ERROR',
            'class': 'pybrake.LoggingHandler',
        },
    },
    'loggers': {
        'app': {
            'handlers': ['airbrake'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
```

then you must provide the name of the logger when making an instance of it.

```py
import logging

logger = logging.getLogger('app')

```

To avoid having to specify a handle name, change the root logger configuration as shown below. [See More Here in Django Doc](https://docs.djangoproject.com/en/4.0/topics/logging/)

```py

'root': {
        'handlers': ['airbrake', 'console'],
        'level': 'ERROR',
    },

```

Django manages all the logs in this way.

**Comment by sandeepbalagopal09** [comment]
Thanks! @sandeepbalagopal09 it worked
