### ISSUE TITLE
No way to filter sensitive args or kwargs

### ISSUE THREAD

**Issue by mrasband** [airbrake/pybrake#64]
Many companies may provide functions with sensitive data that they do not want to expose, there should be a way to filter/scrub/mask function arguments from a source that can throw an exception. In the docs, `keys_blacklist` could be misinterpreted to indicate this.

**Comment by vmihailenco** [comment]
`keys_blacklist` allows to filter sensitive data by keys. If you want to filter data by values you could write your own filter and add it using `add_filter`  - https://github.com/airbrake/pybrake/blob/master/pybrake/notifier.py#L85-L91. I don't think we are going to provide such function out of the box.

**Comment by mrasband** [comment]
I'll see if I can write a sample test case or make a sample app to demonstrate, as the unfiltered `args` are attached to `extra > data > args` (if it's relevant that is through the `pybrake.LoggingHandler`). I have the `keys_blacklist` set up and am not witnessing what you are indicating.
