### ISSUE TITLE
log message arguments not merged as expected by Python's standard log interface

### ISSUE THREAD

**Issue by eastside** [airbrake/pybrake#81]
According to the [official documentation for Python's logging module](https://docs.python.org/3/library/logging.html#logging.debug
), the interface for logging should be as follows:

> **```logging.debug(msg, *args, **kwargs)```**
> Logs a message with level DEBUG on the root logger. The msg is the message format string, and _the args are the arguments which are merged into msg using the string formatting operator_.

Here's an example:

```
import logging
log = logging.getLogger(__name__)
log.error("This is my error: %s", 123)
```

One would expect the logged message to be "This is my error: 123." 

Pybrake, however, does not respect this interface. The logged message is "This is my error: %s". The "args" are not merged into "msg" as per the standard interface.

After reviewing the source code, I'm fairly certain the problem is here:

https://github.com/airbrake/pybrake/blob/9693af1894f0969df52d6cf8225e272e42450d1a/pybrake/logging.py#L57

This should be changed to

```
message=record.getMessage()
```

Using the standard [library's getMessage() method](https://github.com/python/cpython/blob/79b5d29041bd85ea3baa050b3fa2481344ea35c9/Lib/logging/__init__.py#L373).

**Comment by vmihailenco** [comment]
Thanks for the report and analysis - should be fixed in master branch.
